### ISSUE TITLE
希望增加松下Lumix Logo，谢谢

### ISSUE THREAD

**Issue by danaquentin** [zhiweio/picseal#3]
![Panasonic-LUMIX-Logo](https://github.com/user-attachments/assets/6ac3b1c9-3bf3-4a6d-a0f6-309cb814ed29)
希望增加松下Lumix Logo，谢谢

**Comment by zhiweio** [comment]
> ![Panasonic-LUMIX-Logo](https://github.com/user-attachments/assets/6ac3b1c9-3bf3-4a6d-a0f6-309cb814ed29)
> 希望增加松下Lumix Logo，谢谢
> 

方便提供一张松下相机拍摄的照片吗

**Comment by zhiweio** [comment]
https://github.com/zhiweio/picseal/pull/4

**Comment by danaquentin** [comment]
![P1008193 2](https://github.com/user-attachments/assets/94dced6c-ba4a-44c2-900a-a94a4968b601)
![P1007110-1](https://github.com/user-attachments/assets/c43414e6-78d4-4081-b91c-9c1962545923)
![P1007393](https://github.com/user-attachments/assets/08182bd2-15ed-4cb1-9420-36d2a03b8c12)
